### ISSUE TITLE
Not Working For Me

### ISSUE THREAD

**Issue by jesslowenberg** [Rezaaa/english-and-persian-lorem-ipsum#1]
Nothin happens when I select the app in the menu dropdown.

**Comment by aminroosta** [comment]
Same here.

**Comment by rezaaa** [comment]
@jesslowenberg @aminroosta which version are you using?

**Comment by aminroosta** [comment]
@Rezaaa Thanks for your reply.
I'm using "Version 41.2 (35397)".

**Comment by omnidesign** [comment]
same for me :/

**Comment by omnidesign** [comment]
I even downgraded to version 40.3 but still not working for me

**Comment by rezaaa** [comment]
@jesslowenberg @omnidesign @aminroosta It should be fine now, I fixed the issues with newer versions.
